trigger:
  branches:
    include:
      - main
      - dev

variables:
  major: 1
  minor: 4
  patch: 2

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- script: dotnet format --verify-no-changes ./task1
  displayName: "Lint C#"

- script: echo "Version: $(major).$(minor).$(patch).$(Build.BuildId)"
  displayName: "Tag version"
