trigger:
  branches:
    include:
      - main
      - dev

variables:
  major: 1
  minor: 4
  patch: 2

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- script: dotnet format --verify-no-changes ./task1
  displayName: "Lint C#"

- script: |
    echo "Version: $(major).$(minor).$(patch).$(Build.BuildId)"

    git config user.email "azure-devops@local"
    git config user.name "azure-devops"

    git remote set-url origin https://$(GITHUB_TOKEN)@github.com/Taratay/intro_project.git

    git tag v$(major).$(minor).$(patch).$(Build.BuildId)
    git push origin v$(major).$(minor).$(patch).$(Build.BuildId)
  displayName: "Tag and push"